apiVersion: v1
kind: PersistentVolume
metadata:
  name: apps-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  storageClassName: local-path
